export const dummyCampaigns = [
  {
    _id: "camp_001",
    title: "Web3 Onboarding Quest",
    description: "Complete tasks to learn Web3 basics and earn rewards.",
    project_name: "Nexura",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 1240,
    maxParticipants: 2000,
    starts_at: "2026-05-01",
    ends_at: "2026-06-01",
    isLive: true,
    reward: { xp: 500, trustTokens: 20 },
    from: "homepage",
  },
  {
    _id: "camp_002",
    title: "AI Builder Sprint",
    description: "Build simple AI tools and get rewarded for participation.",
    project_name: "ReFi AI",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 860,
    maxParticipants: 1500,
    starts_at: "2026-05-03",
    ends_at: "2026-06-10",
    isLive: true,
    reward: { xp: 750, pool: 3000 },
    from: "explore",
  },
  {
    _id: "camp_003",
    title: "DeFi Fundamentals",
    description: "Learn decentralized finance step by step.",
    project_name: "ChainLearn",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 2300,
    maxParticipants: 3000,
    starts_at: "2026-04-20",
    ends_at: "2026-05-30",
    isLive: true,
    reward: { xp: 300 },
    from: "homepage",
  },
  {
    _id: "camp_004",
    title: "Smart Contract Bootcamp",
    description: "Hands-on Solidity challenges for beginners.",
    project_name: "SolBase",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 540,
    maxParticipants: 1000,
    starts_at: "2026-05-05",
    ends_at: "2026-06-05",
    isLive: true,
    reward: { xp: 1000, trust: 50 },
    from: "learn",
  },
  {
    _id: "camp_005",
    title: "Frontend UI Challenge",
    description: "Recreate real-world UI components under time pressure.",
    project_name: "UIForge",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 780,
    maxParticipants: 1200,
    starts_at: "2026-04-28",
    ends_at: "2026-05-28",
    isLive: true,
    reward: { xp: 650 },
    from: "explore",
  },
  {
    _id: "camp_006",
    title: "Crypto Security Basics",
    description: "Understand wallet safety and smart contract risks.",
    project_name: "SafeChain",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 1900,
    maxParticipants: 2500,
    starts_at: "2026-05-02",
    ends_at: "2026-06-15",
    isLive: true,
    reward: { xp: 400, trustTokens: 10 },
    from: "security",
  },
  {
    _id: "camp_007",
    title: "Hackathon Prep Quest",
    description: "Prepare for real hackathons with guided tasks.",
    project_name: "BuildX",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 430,
    maxParticipants: 800,
    starts_at: "2026-05-08",
    ends_at: "2026-06-20",
    isLive: true,
    reward: { xp: 900, pool: 5000 },
    from: "hack",
  },
  {
    _id: "camp_008",
    title: "Node.js Mastery Path",
    description: "Backend development challenges from beginner to advanced.",
    project_name: "BackendLab",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 1120,
    maxParticipants: 1800,
    starts_at: "2026-04-25",
    ends_at: "2026-05-25",
    isLive: true,
    reward: { xp: 1200 },
    from: "learn",
  },
  {
    _id: "camp_009",
    title: "UI Animation Challenge",
    description: "Create smooth, modern UI animations using CSS & JS.",
    project_name: "MotionLab",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 610,
    maxParticipants: 900,
    starts_at: "2026-05-10",
    ends_at: "2026-06-10",
    isLive: true,
    reward: { xp: 700, trust: 25 },
    from: "ui",
  },
  {
    _id: "camp_010",
    title: "Blockchain Explorer Quest",
    description: "Understand how transactions and blocks really work.",
    project_name: "ChainCore",
    projectLogo: "/quest-1.png",
    projectCoverImage: "/quest-1.png",
    participants: 2750,
    maxParticipants: 4000,
    starts_at: "2026-04-18",
    ends_at: "2026-06-30",
    isLive: true,
    reward: { xp: 500 },
    from: "blockchain",
  },
];